// Generated by Scripts/generate_fsrs_vectors.py from py-fsrs 4.1.2 (FSRS v5).
// Do not edit by hand — regenerate instead.

struct FSRSVectorStep {
    let rating: Int
    let reviewOffset: Double  // seconds from scenario start
    let state: Int            // py-fsrs: 1=learning 2=review 3=relearning
    let step: Int?
    let stability: Double
    let difficulty: Double
    let intervalSeconds: Double
}

struct FSRSVectorScenario {
    let name: String
    let steps: [FSRSVectorStep]
}

enum FSRSTestVectors {
    static let scenarios: [FSRSVectorScenario] = [
        FSRSVectorScenario(name: "new-again", steps: [
            FSRSVectorStep(rating: 1, reviewOffset: 0.0, state: 1, step: 0, stability: 0.40255, difficulty: 7.1949, intervalSeconds: 60.0),
        ]),
        FSRSVectorScenario(name: "new-hard", steps: [
            FSRSVectorStep(rating: 2, reviewOffset: 0.0, state: 1, step: 0, stability: 1.18385, difficulty: 6.488305268471453, intervalSeconds: 330.0),
        ]),
        FSRSVectorScenario(name: "new-good", steps: [
            FSRSVectorStep(rating: 3, reviewOffset: 0.0, state: 1, step: 1, stability: 3.173, difficulty: 5.282434422319005, intervalSeconds: 600.0),
        ]),
        FSRSVectorScenario(name: "new-easy", steps: [
            FSRSVectorStep(rating: 4, reviewOffset: 0.0, state: 2, step: nil, stability: 15.69105, difficulty: 3.2245015893713678, intervalSeconds: 1382400.0),
        ]),
        FSRSVectorScenario(name: "graduate-good", steps: [
            FSRSVectorStep(rating: 3, reviewOffset: 0.0, state: 1, step: 1, stability: 3.173, difficulty: 5.282434422319005, intervalSeconds: 600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 600.0, state: 2, step: nil, stability: 4.466858064362218, difficulty: 5.272967931287446, intervalSeconds: 345600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 346200.0, state: 2, step: nil, stability: 14.217284109332127, difficulty: 5.263544986114632, intervalSeconds: 1209600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 1555800.0, state: 2, step: nil, stability: 43.72509406220378, difficulty: 5.254165386489613, intervalSeconds: 3801600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 5357400.0, state: 2, step: nil, stability: 124.79655604607703, difficulty: 5.244828933022869, intervalSeconds: 10800000.0),
            FSRSVectorStep(rating: 3, reviewOffset: 16157400.0, state: 2, step: nil, stability: 328.4734410094181, difficulty: 5.2355354272420715, intervalSeconds: 28339200.0),
            FSRSVectorStep(rating: 3, reviewOffset: 44496600.0, state: 2, step: nil, stability: 805.6082939815602, difficulty: 5.226284671587866, intervalSeconds: 69638400.0),
            FSRSVectorStep(rating: 3, reviewOffset: 114135000.0, state: 2, step: nil, stability: 1860.6540568001226, difficulty: 5.21707646940967, intervalSeconds: 160790400.0),
        ]),
        FSRSVectorScenario(name: "lapse-cycle", steps: [
            FSRSVectorStep(rating: 3, reviewOffset: 0.0, state: 1, step: 1, stability: 3.173, difficulty: 5.282434422319005, intervalSeconds: 600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 600.0, state: 2, step: nil, stability: 4.466858064362218, difficulty: 5.272967931287446, intervalSeconds: 345600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 346200.0, state: 2, step: nil, stability: 14.217284109332127, difficulty: 5.263544986114632, intervalSeconds: 1209600.0),
            FSRSVectorStep(rating: 1, reviewOffset: 1555800.0, state: 3, step: 0, stability: 2.504170139105898, difficulty: 6.784232087673549, intervalSeconds: 600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 1556400.0, state: 2, step: nil, stability: 3.5252986386385876, difficulty: 6.767857327381359, intervalSeconds: 345600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 1902000.0, state: 2, step: nil, stability: 10.760826101730665, difficulty: 6.751557890986513, intervalSeconds: 950400.0),
            FSRSVectorStep(rating: 3, reviewOffset: 2852400.0, state: 2, step: nil, stability: 28.4443180529374, difficulty: 6.735333431999083, intervalSeconds: 2419200.0),
        ]),
        FSRSVectorScenario(name: "hard-path", steps: [
            FSRSVectorStep(rating: 3, reviewOffset: 0.0, state: 1, step: 1, stability: 3.173, difficulty: 5.282434422319005, intervalSeconds: 600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 600.0, state: 2, step: nil, stability: 4.466858064362218, difficulty: 5.272967931287446, intervalSeconds: 345600.0),
            FSRSVectorStep(rating: 2, reviewOffset: 346200.0, state: 2, step: nil, stability: 6.724081693772751, difficulty: 6.0270563403407795, intervalSeconds: 604800.0),
            FSRSVectorStep(rating: 2, reviewOffset: 951000.0, state: 2, step: nil, stability: 9.943158569463549, difficulty: 6.655875401900955, intervalSeconds: 864000.0),
            FSRSVectorStep(rating: 3, reviewOffset: 1815000.0, state: 2, step: nil, stability: 26.564252692669662, difficulty: 6.640091082363319, intervalSeconds: 2332800.0),
            FSRSVectorStep(rating: 4, reviewOffset: 4147800.0, state: 2, step: nil, stability: 146.2114835848994, difficulty: 6.0816860759407385, intervalSeconds: 12614400.0),
        ]),
        FSRSVectorScenario(name: "easy-immediate", steps: [
            FSRSVectorStep(rating: 4, reviewOffset: 0.0, state: 2, step: nil, stability: 15.69105, difficulty: 3.2245015893713678, intervalSeconds: 1382400.0),
            FSRSVectorStep(rating: 3, reviewOffset: 1382400.0, state: 2, step: nil, stability: 60.708278951323095, difficulty: 3.2245015893713673, intervalSeconds: 5270400.0),
            FSRSVectorStep(rating: 3, reviewOffset: 6652800.0, state: 2, step: nil, stability: 206.99233149775762, difficulty: 3.224501589371367, intervalSeconds: 17884800.0),
        ]),
        FSRSVectorScenario(name: "hard-first", steps: [
            FSRSVectorStep(rating: 2, reviewOffset: 0.0, state: 1, step: 0, stability: 1.18385, difficulty: 6.488305268471453, intervalSeconds: 330.0),
            FSRSVectorStep(rating: 2, reviewOffset: 330.0, state: 1, step: 0, stability: 0.9942462110608663, difficulty: 7.040501547390819, intervalSeconds: 330.0),
            FSRSVectorStep(rating: 3, reviewOffset: 660.0, state: 1, step: 1, stability: 1.3996711962933535, difficulty: 7.022947947583929, intervalSeconds: 600.0),
            FSRSVectorStep(rating: 3, reviewOffset: 1260.0, state: 2, step: nil, stability: 1.9704168202390417, difficulty: 7.005475094336151, intervalSeconds: 172800.0),
        ]),
    ]
}

