// swift-tools-version: 6.0
// The pure-Swift core (Domain + Application + Infrastructure) lives in this package
// so `swift test` runs without Xcode. The macOS app target (Sources/Presentation)
// is generated by XcodeGen (project.yml) and depends on these products.
import PackageDescription

let package = Package(
    name: "RecallCore",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "Domain", targets: ["Domain"]),
        .library(name: "Application", targets: ["Application"]),
        .library(name: "Infrastructure", targets: ["Infrastructure"]),
    ],
    targets: [
        .target(name: "Domain", path: "Sources/Domain"),
        .target(name: "Application", dependencies: ["Domain"], path: "Sources/Application"),
        .target(name: "Infrastructure", dependencies: ["Domain"], path: "Sources/Infrastructure"),
        .testTarget(
            name: "DomainTests",
            dependencies: ["Domain", "Application"],
            path: "Tests/DomainTests"
        ),
    ],
    swiftLanguageModes: [.v6]
)
