"""Generate FSRS reference vectors from py-fsrs 4.1.2 (FSRS v5) as a Swift file."""

from datetime import datetime, timezone, timedelta
from fsrs import Scheduler, Card, Rating

START = datetime(2025, 1, 1, 12, 0, 0, tzinfo=timezone.utc)

# name -> list of (rating, when). when = "due" (review exactly at card.due) or seconds offset from START.
SCENARIOS = {
    "new-again": [(Rating.Again, 0)],
    "new-hard": [(Rating.Hard, 0)],
    "new-good": [(Rating.Good, 0)],
    "new-easy": [(Rating.Easy, 0)],
    "graduate-good": [(Rating.Good, 0)] + [(Rating.Good, "due")] * 7,
    "lapse-cycle": [
        (Rating.Good, 0), (Rating.Good, "due"), (Rating.Good, "due"),
        (Rating.Again, "due"), (Rating.Good, "due"), (Rating.Good, "due"), (Rating.Good, "due"),
    ],
    "hard-path": [
        (Rating.Good, 0), (Rating.Good, "due"), (Rating.Hard, "due"),
        (Rating.Hard, "due"), (Rating.Good, "due"), (Rating.Easy, "due"),
    ],
    "easy-immediate": [(Rating.Easy, 0), (Rating.Good, "due"), (Rating.Good, "due")],
    "hard-first": [(Rating.Hard, 0), (Rating.Hard, "due"), (Rating.Good, "due"), (Rating.Good, "due")],
}


def run(name, steps):
    scheduler = Scheduler(enable_fuzzing=False)
    card = Card(card_id=1, due=START)
    out = []
    for rating, when in steps:
        review_dt = card.due if when == "due" else START + timedelta(seconds=when)
        card, _ = scheduler.review_card(card, rating, review_dt)
        out.append({
            "rating": int(rating),
            "reviewOffset": (review_dt - START).total_seconds(),
            "state": int(card.state),
            "step": card.step,
            "stability": card.stability,
            "difficulty": card.difficulty,
            "intervalSeconds": (card.due - review_dt).total_seconds(),
        })
    return out


lines = [
    "// Generated by Scripts/generate_fsrs_vectors.py from py-fsrs 4.1.2 (FSRS v5).",
    "// Do not edit by hand — regenerate instead.",
    "",
    "struct FSRSVectorStep {",
    "    let rating: Int",
    "    let reviewOffset: Double  // seconds from scenario start",
    "    let state: Int            // py-fsrs: 1=learning 2=review 3=relearning",
    "    let step: Int?",
    "    let stability: Double",
    "    let difficulty: Double",
    "    let intervalSeconds: Double",
    "}",
    "",
    "struct FSRSVectorScenario {",
    "    let name: String",
    "    let steps: [FSRSVectorStep]",
    "}",
    "",
    "enum FSRSTestVectors {",
    "    static let scenarios: [FSRSVectorScenario] = [",
]
for name, steps in SCENARIOS.items():
    lines.append(f'        FSRSVectorScenario(name: "{name}", steps: [')
    for s in run(name, steps):
        step = "nil" if s["step"] is None else str(s["step"])
        lines.append(
            f'            FSRSVectorStep(rating: {s["rating"]}, reviewOffset: {s["reviewOffset"]!r}, '
            f'state: {s["state"]}, step: {step}, stability: {s["stability"]!r}, '
            f'difficulty: {s["difficulty"]!r}, intervalSeconds: {s["intervalSeconds"]!r}),'
        )
    lines.append("        ]),")
lines += ["    ]", "}", ""]
print("\n".join(lines))
