import Foundation

/// A typed field declaration inside a `NoteType`.
public struct FieldDef: Sendable, Codable, Hashable {
    public var name: String
    public var contentType: ContentType

    public init(name: String, contentType: ContentType = .markdown) {
        self.name = name
        self.contentType = contentType
    }
}

/// Defines one card generated from a note: which fields make up each side.
public struct CardTemplate: Sendable, Codable, Hashable {
    public var name: String
    public var frontFieldRefs: [String]
    public var backFieldRefs: [String]

    public init(name: String, frontFieldRefs: [String], backFieldRefs: [String]) {
        self.name = name
        self.frontFieldRefs = frontFieldRefs
        self.backFieldRefs = backFieldRefs
    }
}

/// Seam 1 (the most important one): a card is NOT "front + back". A note has N typed
/// fields and its note type decides how many cards it generates and what each side shows.
/// MVP ships only `.basic`; reversed/cloze/typed-answer plug in here later.
public struct NoteType: Identifiable, Sendable, Codable, Hashable {
    public let id: UUID
    public var name: String
    public var fields: [FieldDef]
    public var templates: [CardTemplate]

    public init(id: UUID = UUID(), name: String, fields: [FieldDef], templates: [CardTemplate]) {
        self.id = id
        self.name = name
        self.fields = fields
        self.templates = templates
    }

    /// The single built-in MVP note type. Fixed UUID so persistence can seed it idempotently.
    public static let basic = NoteType(
        id: UUID(uuidString: "00000000-0000-0000-0000-000000000001")!,
        name: "Basic",
        fields: [FieldDef(name: "front"), FieldDef(name: "back")],
        templates: [CardTemplate(name: "Card 1", frontFieldRefs: ["front"], backFieldRefs: ["back"])]
    )

    /// One card per template — the hook that lets future note types generate 2+ cards.
    public func makeCards(for note: Note, createdAt: Date) -> [Card] {
        precondition(note.noteTypeID == id, "note belongs to a different note type")
        return templates.indices.map { index in
            Card(noteID: note.id, templateIndex: index, deckID: note.deckID, createdAt: createdAt)
        }
    }

    /// A field resolved against a concrete note, ready for the content renderer.
    public struct RenderableField: Sendable, Hashable {
        public let def: FieldDef
        public let content: String
    }

    /// Front side of the card generated by `templateIndex`. UI must always go through
    /// these — there is no `card.front`.
    public func frontFields(of note: Note, templateIndex: Int) -> [RenderableField] {
        resolve(refs: templates[templateIndex].frontFieldRefs, note: note)
    }

    public func backFields(of note: Note, templateIndex: Int) -> [RenderableField] {
        resolve(refs: templates[templateIndex].backFieldRefs, note: note)
    }

    private func resolve(refs: [String], note: Note) -> [RenderableField] {
        refs.compactMap { ref in
            guard let def = fields.first(where: { $0.name == ref }) else { return nil }
            return RenderableField(def: def, content: note.fields[ref] ?? "")
        }
    }
}
