import Foundation

/// A typed field declaration inside a `NoteType`.
public struct FieldDef: Sendable, Codable, Hashable {
    public var name: String
    public var contentType: ContentType

    public init(name: String, contentType: ContentType = .markdown) {
        self.name = name
        self.contentType = contentType
    }
}

/// Defines one card generated from a note: which fields make up each side.
public struct CardTemplate: Sendable, Codable, Hashable {
    public var name: String
    public var frontFieldRefs: [String]
    public var backFieldRefs: [String]

    public init(name: String, frontFieldRefs: [String], backFieldRefs: [String]) {
        self.name = name
        self.frontFieldRefs = frontFieldRefs
        self.backFieldRefs = backFieldRefs
    }
}

/// How a note type turns fields into cards and card sides.
public enum NoteTypeKind: String, Sendable, Codable, Hashable {
    /// Static templates: one card per `CardTemplate`.
    case basic
    /// One card per `{{cN::answer}}` marker in the "text" field.
    case cloze
    /// Like basic, but `{a}` placeholders regenerate from the "variables" field
    /// on every review — practice the procedure, not the answer.
    case parametric
}

/// Seam 1 (the most important one): a card is NOT "front + back". A note has N typed
/// fields and its note type decides how many cards it generates and what each side shows.
public struct NoteType: Identifiable, Sendable, Codable, Hashable {
    public let id: UUID
    public var name: String
    public var kind: NoteTypeKind
    public var fields: [FieldDef]
    public var templates: [CardTemplate]

    public init(
        id: UUID = UUID(), name: String, kind: NoteTypeKind = .basic,
        fields: [FieldDef], templates: [CardTemplate]
    ) {
        self.id = id
        self.name = name
        self.kind = kind
        self.fields = fields
        self.templates = templates
    }

    /// Built-in types. Fixed UUIDs so persistence can seed them idempotently.
    public static let basic = NoteType(
        id: UUID(uuidString: "00000000-0000-0000-0000-000000000001")!,
        name: "Basic",
        fields: [FieldDef(name: "front"), FieldDef(name: "back")],
        templates: [CardTemplate(name: "Card 1", frontFieldRefs: ["front"], backFieldRefs: ["back"])]
    )

    public static let cloze = NoteType(
        id: UUID(uuidString: "00000000-0000-0000-0000-000000000002")!,
        name: "Cloze",
        kind: .cloze,
        fields: [FieldDef(name: "text")],
        templates: [] // dynamic: one card per {{cN::…}} in the text
    )

    public static let parametric = NoteType(
        id: UUID(uuidString: "00000000-0000-0000-0000-000000000003")!,
        name: "Parametric",
        kind: .parametric,
        fields: [FieldDef(name: "front"), FieldDef(name: "back"), FieldDef(name: "variables")],
        templates: [CardTemplate(name: "Card 1", frontFieldRefs: ["front"], backFieldRefs: ["back"])]
    )

    public static let builtIns: [NoteType] = [.basic, .cloze, .parametric]

    /// Template indices a note of this type should have cards for.
    public func templateIndices(for note: Note) -> [Int] {
        switch kind {
        case .basic, .parametric:
            Array(templates.indices)
        case .cloze:
            // {{c2::…}} maps to templateIndex 1, so adding c3 later never renumbers
            // existing cards.
            Cloze.indices(in: note.fields["text"] ?? "").map { $0 - 1 }
        }
    }

    /// One card per template index — cloze notes generate one per marker.
    public func makeCards(for note: Note, createdAt: Date) -> [Card] {
        precondition(note.noteTypeID == id, "note belongs to a different note type")
        return templateIndices(for: note).map { index in
            Card(noteID: note.id, templateIndex: index, deckID: note.deckID, createdAt: createdAt)
        }
    }

    /// A field resolved against a concrete note, ready for the content renderer.
    public struct RenderableField: Sendable, Hashable {
        public let def: FieldDef
        public let content: String
    }

    /// Front side of the card generated by `templateIndex`. UI must always go through
    /// these — there is no `card.front`. `seed` drives parametric substitution;
    /// nil renders the raw template (editors, browser).
    public func frontFields(of note: Note, templateIndex: Int, seed: UInt64? = nil) -> [RenderableField] {
        sideFields(of: note, templateIndex: templateIndex, front: true, seed: seed) ?? []
    }

    public func backFields(of note: Note, templateIndex: Int, seed: UInt64? = nil) -> [RenderableField] {
        sideFields(of: note, templateIndex: templateIndex, front: false, seed: seed) ?? []
    }

    /// nil when `templateIndex` is stale for this note (e.g. a removed cloze marker).
    public func sideFields(
        of note: Note, templateIndex: Int, front: Bool, seed: UInt64? = nil
    ) -> [RenderableField]? {
        switch kind {
        case .basic:
            guard templates.indices.contains(templateIndex) else { return nil }
            return resolve(refs: refs(templateIndex: templateIndex, front: front), note: note)
        case .cloze:
            guard let textDef = fields.first else { return nil }
            let text = note.fields[textDef.name] ?? ""
            let clozeNumber = templateIndex + 1
            guard Cloze.indices(in: text).contains(clozeNumber) else { return nil }
            let content = front
                ? Cloze.front(text, hiding: clozeNumber)
                : Cloze.back(text, revealing: clozeNumber)
            return [RenderableField(def: textDef, content: content)]
        case .parametric:
            guard templates.indices.contains(templateIndex) else { return nil }
            let raw = resolve(refs: refs(templateIndex: templateIndex, front: front), note: note)
            guard let seed else { return raw }
            let values = Parametric.values(spec: note.fields["variables"] ?? "", seed: seed)
            return raw.map {
                RenderableField(def: $0.def, content: Parametric.substitute($0.content, values: values))
            }
        }
    }

    private func refs(templateIndex: Int, front: Bool) -> [String] {
        front ? templates[templateIndex].frontFieldRefs : templates[templateIndex].backFieldRefs
    }

    private func resolve(refs: [String], note: Note) -> [RenderableField] {
        refs.compactMap { ref in
            guard let def = fields.first(where: { $0.name == ref }) else { return nil }
            return RenderableField(def: def, content: note.fields[ref] ?? "")
        }
    }
}
